import 'package:ehosptal_flutter_revamp/View/Screens/AgenticAI/localization/app_strings.dart';

const enStrings = AppStrings(
  languageEnglish: 'English',
  languageFrench: 'Français',
  appEyebrow: 'Connected Analytics',
  appTitle: 'Warehouse Analysis Workspace',
  appCopy:
      'Connect to source databases, load selected tables into the warehouse, and keep a running analysis conversation against the data already onboarded.',
  connectorTitle: 'Database Connector',
  connectorSubtitle:
      'Start with a host connection, then choose a database and the tables you want to load.',
  sourceTypeLabel: 'Source Type',
  sourceTypeDatabase: 'Database',
  sourceTypeTableApi: 'Table API',
  hostPlaceholder: 'Host',
  portPlaceholder: 'Port',
  userPlaceholder: 'User',
  passwordPlaceholder: 'Password',
  apiBaseUrlPlaceholder: 'Base URL',
  apiTokenPlaceholder: 'API Token (optional)',
  tableApiHelper:
      'Use a table API source when the source is exposed as /tables and /table/<name>. Enter the base URL and optionally an API token, then connect and choose tables.',
  connectorHelper:
      'Connection details stay in the current session and are used only for table discovery and load requests.',
  connectSource: 'Connect Source',
  connecting: 'Connecting...',
  connected: 'Connected',
  disconnect: 'Disconnect',
  databaseLabel: 'Database',
  selectDatabase: 'Select a source database',
  loadTablesLabel: 'Load Source Tables',
  loadTables: 'Load tables',
  loadingTables: 'Loading...',
  selectTablesLabel: 'Select Tables',
  filterTables: 'Filter tables',
  chooseTableFirst: 'Choose at least one table to continue.',
  ingestAndRefresh: 'Ingest and Refresh Views',
  loadingWarehouse: 'Loading Into Warehouse...',
  loadedSourcesTitle: 'Loaded Sources',
  loadedSourcesSubtitle:
      'A quick inventory of what has already been pulled into the warehouse.',
  noLoadInventory: 'No warehouse load inventory found yet.',
  sourceHost: 'Source Host',
  refreshAll: 'Refresh all',
  refreshing: 'Refreshing...',
  deleteAll: 'Delete all',
  databasePrefix: 'Database',
  updatedAtPrefix: 'Updated',
  updatedTimeUnavailable: 'Updated time unavailable',
  originalSourceUnknown: 'Original source not tracked.',
  analysisEyebrow: 'Analysis',
  analysisTitle: 'Analytics Chat',
  analysisCopy:
      'Ask follow-up questions naturally. The assistant uses the loaded warehouse views to explain the data with charts and concise analysis.',
  noAnalysisYet: 'No analysis yet.',
  noAnalysisCopy:
      'Load source tables on the left, then start asking questions here. This workspace is designed for iterative exploration, not one-off prompts.',
  aiAnalysis: 'AI Analysis',
  sourcesPrefix: 'Sources',
  qualityFlagsPrefix: 'Quality flags',
  composerHelper:
      'Keep asking follow-ups here. The conversation stays in context for this session.',
  showDebugData: 'Show debug data',
  chatPlaceholder:
      'Ask about revenue, appointments, billing behaviour, lab activity, patient operations, or follow up on a previous answer.',
  analyzing: 'Analyzing...',
  send: 'Send',
  modalEnterCredentials: 'Enter Source Credentials',
  modalEnterCredentialsCopy:
      'This refresh needs the source credentials again before it can continue.',
  refreshOneFrom: 'Refresh {table} from {host}:{port} / {database}',
  refreshAllFrom: 'Refresh all tracked tables from {host}:{port}',
  cancel: 'Cancel',
  retryRefresh: 'Retry Refresh',
  modalLoadDataFirst: 'Load Data First',
  modalLoadDataFirstCopy:
      'Connect a source and ingest at least one table before starting analysis.',
  modalLoadDataFirstHelper:
      'Use the database connector on the left to choose a source, load tables, and bring data into the warehouse.',
  close: 'Close',
  askFailed: 'Analysis request failed.',
  askFailedAnswer: 'I could not complete that analysis request.',
  connectionFailed: 'Connection failed.',
  chooseDatabaseFirst: 'Choose a database first.',
  couldNotLoadTables: 'Could not load tables.',
  selectTableBeforeLoad: 'Select at least one table before loading data.',
  ingestionFailed: 'Ingestion failed.',
  refreshFailed: 'Refresh failed.',
  couldNotDeleteLoadedTable: 'Could not delete the loaded table.',
  couldNotDeleteLoadedGroup: 'Could not delete the loaded source group.',
  loadedSummary:
      'Loaded {count} table{suffix} into the warehouse and refreshed the analysis layer.',
  processedSummary: 'Processed {count} selected table{suffix}.',
  selectedTablesSummary: '{count} table{suffix} selected for ingestion.',
  loadedDot: 'loaded',
  confirmDeleteGroup: 'Delete all loaded tables for {label}?',
  resultSeries: 'Result',
  demoQuestions: <String>[
    'What month do we make the most money?',
    'Show weekly revenue trend.',
    'Which doctors have the most completed appointments?',
    'How many bills are paid vs unpaid vs rejected?',
    'Most common blood tests.',
  ],
);